// Generated by CoffeeScript 1.3.3
(function() {

  window._R_ = (function() {

    function _R_(window) {
      this.window = window != null ? window : window;
      this.stops = {};
    }

    _R_.prototype.is = function(stop) {
      var query;
      stop = this.stops[stop];
      if (stop != null) {
        query = this.window.matchMedia(stop);
        return query.matches;
      } else {
        return false;
      }
    };

    _R_.prototype.isnt = function(stop) {
      return !this.is(stop);
    };

    return _R_;

  })();

  window.R = new _R_(window);

}).call(this);
